### ISSUE TITLE
Avalonia dependency version leading to errors in GUI project

### ISSUE THREAD

**Issue by YuumiPie** [kabiiQ/BeatmapExporter#18]
Setting the version of the Avalonia dependencies to "$(AvaloniaVersion)" leads to the dependency being set to the earliest version (0.4.0). The version is incompatible with the GUI project. One possible solution is to have it explicitly set to a compatible version.

https://github.com/kabiiQ/BeatmapExporter/blob/cac14c000e45b4fcbf1c6866b6f616324d2c34db/BeatmapExporterGUI/BeatmapExporterGUI.csproj#L20-L28

**Comment by kabiiQ** [comment]
cf49cca5041aa3e3ecff3a0f134a4ea19dc72e84
