### ISSUE TITLE
database structure updated

### ISSUE THREAD

**Issue by UnsavedTrash** [kabiiQ/BeatmapExporter#19]
``` --- kabii's Lazer Exporter ---

Checking directory: /home/ut/.local/share/osu
Run this application with your osu!lazer storage directory as an argument if this is not your osu! data location.
The osu!lazer database structure has updated since the last BeatmapExporter update.

You can check https://github.com/kabiiQ/BeatmapExporter/releases for a new release, or file an issue there to let me know it needs updating if it's been a few days.
```
I am unable to extract maps with both the GUI and the CLI versions of the app. I am currently running on Arch linux with the flatpak version of osu. The GUI launcher provides no errors and simply refuses to accept the directory for the files when called via my file browser.

**Comment by kabiiQ** [comment]
Please make sure your osu!lazer is updated to version 2024.512.2. 

If you did already update, this is probably related to a previous issue #12. It seems like the Linux version is sometimes behind on the database revision despite version numbers matching? If you could try to just use 2.0.0 or 2.1.0 pre-release instead: https://github.com/kabiiQ/BeatmapExporter/releases/tag/v2.1.0-pre3

I do see from the error message you posted that I made a change which stopped the exact error message with database version numbers being displayed, I will revert that change for future releases.

**Comment by UnsavedTrash** [comment]
I see, my data was stored in the flatpak data storage area. It seems both the GUI and CLI versions work fine once I started pointing them to `/home/[username]/.var/app/sh.ppy.osu/data/osu/` which is the flatpak data storage location. Thank you for the patience and assistance with this.
