### ISSUE TITLE
Error Opening Database

### ISSUE THREAD

**Issue by KiwiKin1** [kabiiQ/BeatmapExporter#2]
![image](https://user-images.githubusercontent.com/106151046/222968166-94c95afa-a052-4e75-a860-4f9ec6ae5ecc.png)

Windows 11 22H2, Osu-Lazer 2023.305.0 as of 3/5/2023.
I open the exe as admin and choose the right directory, but It's show as the image above multiple times of trying, is it my issues or it not work for newer version of lazer?

**Comment by kabiiQ** [comment]
Definitely broken once you launch 2023.305.0. Pushing an update in a bit. 

Not sure when they made the changes that broke it, the error message is weird too because the "version" was not changed in lazer, they just added some new data fields at some point.

**Comment by kabiiQ** [comment]
https://github.com/kabiiQ/BeatmapExporter/releases/tag/v1.2.12

**Comment by kabiiQ** [comment]
https://github.com/kabiiQ/BeatmapExporter/releases/tag/v1.2.12
