### ISSUE TITLE
How to use it on Mac?

### ISSUE THREAD

**Issue by gamerturtlepoggers** [kabiiQ/BeatmapExporter#20]
I've downloaded the osx-BeatmapExporter file and I am not sure how to use it to export my beatmap files/replays. 
My situation is I have lost my osu files but I am trying to use a backup save of my osu folder and export it into the osz and osr files and then reimport it back into osu

I![Screenshot 2024-07-04 at 10 31 50 AM](https://github.com/kabiiQ/BeatmapExporter/assets/83538469/e1086eb6-02e4-4742-a642-a1dfa48b5588)

**Comment by kabiiQ** [comment]
Hi, I haven't used a Mac really ever, but I believe you will need to mark the file executable before running it. See: https://support.apple.com/guide/terminal/make-a-file-executable-apdd100908f-06b3-4e63-8a87-32e71241bab4/mac

Just to verify, you have a backup of an osu!lazer folder (containing a client.realm file)? If so, it should be straightforward to open that backup folder once you get the program running.

**Comment by gamerturtlepoggers** [comment]
Hi, thanks for the quick reply.
Hi I have the program running, but when I link my osu backups folder it doesn't work, also all my beatmaps are showing as 0.00 stars. I am really lost

**Comment by kabiiQ** [comment]
Not much to go on here currently. 

Do you have screenshots of what doesn't work? Such as what it shows when you try to open your osu folder.
