### ISSUE TITLE
MacOS unable to install

### ISSUE THREAD

**Issue by TurtleHumanthecreator** [kabiiQ/BeatmapExporter#22]
Downloaded file is unable to be opened on MacOS (CLI and UI versions)

**Comment by kabiiQ** [comment]
I've never really even touched MacOS so I won't be able to provide specific screenshots or really be more useful than Google. I do have users who have used the program on Mac and it worked as expected. However, some level of Terminal usage will be required.

Running a basic executable program like osx-BeatmapExporter will require the use of your Terminal to mark it executable and run it. See https://support.apple.com/guide/terminal/make-a-file-executable-apdd100908f-06b3-4e63-8a87-32e71241bab4/mac
