### ISSUE TITLE
Latest schema version (43) not supported.

### ISSUE THREAD

**Issue by solsahar** [kabiiQ/BeatmapExporter#23]
Also tried building from source, same issue.

**Comment by kabiiQ** [comment]
[2.2.2](https://github.com/kabiiQ/BeatmapExporter/releases/tag/v2.2.2) definitely supports schema version 43 (and only 43). Can you share the exact error message about schema version that you are seeing?

**Comment by solsahar** [comment]
![image](https://github.com/user-attachments/assets/ff9fa3bf-0d9e-4cdd-a171-206c644825e3)

I reset my computer & had to transfer files from my old computer to my new one. I copied the whole OSU folder onto my new pc and am now trying to extract the beatmaps.

**Comment by kabiiQ** [comment]
You'll want to use [2.2.1](https://github.com/kabiiQ/BeatmapExporter/releases/tag/v2.2.1) instead of the latest 2.2.2. The database you are accessing is on 42, which makes sense if you haven't launched the latest osu!lazer from 3 days ago it'll be on the older version still.

**Comment by solsahar** [comment]
Alrighty, that worked! Thank you!
