### ISSUE TITLE
"Realm accessed from incorrect thread" after transcoding

### ISSUE THREAD

**Issue by Ecasept** [kabiiQ/BeatmapExporter#24]
When I use the CLI version, all files that need transcoding fail with a similiar error message.
Example:
```
(393/?) Exporting YOASOBI - Yuusha (TV Size).mp3(transcode required from .ogg)
Unable to set metadata for YOASOBI - Yuusha (TV Size).mp3 :: Realm accessed from incorrect thread.
Exporting will continue.
```
This does not happen when I use the GUI version.

### Steps to reproduce
- Start CLI
- Under advanced export settings, select "Type 2"
- Export audio files

**Version**: 2.2.2
**OS**: Fedora Linux 40

**Comment by kabiiQ** [comment]
Thanks for the report. [BeatmapExporter 2.2.3](https://github.com/kabiiQ/BeatmapExporter/releases/tag/v2.2.3) should fix this behavior.

The transcoded files should have still been exporting. Just the metadata (song artist, title) would have failed to apply to those files, so the result of this bug should've been pretty minor overall. This actually affected both CLI and GUI, but only the CLI displayed the error while the GUI just kept going without waiting for the encode to finish (a behavior I was aware of but thought it was fine at the time). Addressing the "thread" issue also fixes this, so the progress bar makes a lot more sense now.
