### ISSUE TITLE
Whether this work on Flatpak

### ISSUE THREAD

**Issue by dhupee** [kabiiQ/BeatmapExporter#3]
I'm not sure whether this is gonna actually work from flatpak version, but i tried on its directory and it didnt really work

may i have confirmation if it actually works on flatpak or you maybe havent try it

**Comment by kabiiQ** [comment]
I've never heard of this version before.

That said, I can't see the database being done differently between versions - if you point this utility to the folder with the `client.realm` file lazer produces it should be able to read it at least, but I don't know the other details of the environment for this version. It sounds like you've tried it and it doesn't work, so unfortunately that's probably the answer. 

Does it fail to run completely?

**Comment by dhupee** [comment]
Sorry for not responding for almost a week, 2 days ago I move to another Linux distro(Arch Based) and it has Osu Lazer binary and not packaged in flatpak

I just move my stuff and I haven't opened my Osu Lazer yet, but I will keep an update on it


answer for your question is that it doesn't detect the folder even though `client.realm` does exist

**Comment by dhupee** [comment]
sorry to leave this hanging, I moved to EndeavourOS and tested your program again after installing my Lazer with AUR(arch user repository)

it worked flawlessly although I run the program only it detected the folder with `Client.realm` but dont seem to able to export it

but it work when i do `{YOUR PROGRAM NAME} {my lazer dir}`, idk its my lack of understanding or the doc that is a bit confusing

but in the future i might to help on the Readme, since i dont have understanding in C#, GG mate
