### ISSUE TITLE
Export only 1 beatmap

### ISSUE THREAD

**Issue by Robiimadot** [kabiiQ/BeatmapExporter#4]
This is now a problem or bug, i just can't use github but i wanted to ask if i can export only one beatmap with this maybe with a gui interface somehow.

**Comment by kabiiQ** [comment]
You could export only one beatmap using BeatmapExporter by using the filter to select the beatmap by ID. There's not a "gui" but just the command line interface as shown on the main page. 

Not sure exactly what you're wanting to do though. There wouldn't be any advantage exporting a single beatmap over just doing it from the game itself.
